# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

image_path:       https://cdn.faingezicht.com/

# Setup
title:            'Blog AF'
initials:         'AF'
name:             'Avy Faingezicht'
url:              https://www.faingezicht.com
baseurl:          /

author:
  name:           'Avy Faingezicht'
  url:            https://twitter.com/avyfain

kramdown:
  footnote_location: 'my_footnotes'

sass:
  sass_dir: _sass
  style: compressed

social:
  twitter:        https://twitter.com/avyfain
  github:         https://github.com/avyfain
  linkedin:       https://www.linkedin.com/in/avyfaingezicht
  flickr:         https://www.flickr.com/avyfain

plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-include-cache]

paginate:         5

version:          1.1

compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: all
  endings: all
  blanklines: false
  profile: false


defaults:
    -
     scope:
         path: ""
     values:
         lang: en
         base-url: "/"
    -
     scope:
         path: es
     values:
         lang: es
         base-url: "/es/"
