# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

image_path:       https://dl.dropboxusercontent.com/u/16238897/avyfain.io/

# Setup
title:            'Blog AF'
initials:         'AF'
name:             'Avy Faingezicht'
description:      'Where I talk about startups and economics, plus random thoughts. Arguments generally supported by data.'
url:              http://www.faingezicht.com
baseurl:          /

author:
  name:           'Avy Faingezicht'
  url:            https://twitter.com/avyfain

social:
  twitter:        https://twitter.com/avyfain
  github:         https://github.com/avyfain
  linkedin:       https://www.linkedin.com/in/avyfaingezicht
  flickr:         https://www.flickr.com/avyfain

gems:             [jekyll-paginate]

paginate:         5

version:          1.0
